export enum ChargingStatus {
    NOCHARGING = "NOCHARGING",
    CHARGINGPAUSED = "CHARGINGPAUSED",
    CHARGINGERROR = "CHARGINGERROR",
    CHARGINGACTIVE= "CHARGINGACTIVE",
    CHARGINGENDED = "CHARGINGENDED",
    UNKNOWN = "UNKNOWN"
}