export enum RemoteServiceExecutionState {
    INITIATED = "INITIATED",
    DELIVERED = "DELIVERED",
    STARTED = "STARTED",
    PENDING = "PENDING",
    RUNNING = "RUNNING",
    PROV_RUNNING = "PROV_RUNNING",
    EXECUTED = "EXECUTED",
    CANCELLED_WITH_ERROR = "CANCELLED_WITH_ERROR",
    ERROR = "ERROR",
    IGNORED = "IGNORED",
    UNKNOWN = "UNKNOWN"
}